server:
  servlet:
    context-path: /
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 842345
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/
 

mybatis:
  type-aliases-package: com.demo.bean
  mapper-locations: classpath:mapper/*.xml